Add Works and About  Sections
Ahmed-Alfaouq/My-Portfolio pull request #2
Opened 2021-08-12 16:50 UTC by Ahmed-Alfaouq

What I did:
1) Add works section
2) Add about section
3) Test stylelint and hint
4) Fixed some errors

2021-08-12 17:27 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

### Hello @Ahmed-Alfaouq ✋🏼  Your project is great. You are almost done. However there are some issues you should fix. Please fix them then your project will be approved.

### 💯  Nice to have 💯
 
- Your git flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
- You stick to the design.✔️
- You know how to use flexbox very well.✔️
- You use HTML semantic elements correctly.✔️

### ♻️ Request changes ♻️

- [ ] _**Check the comments under the review.**_


### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/3ohzAj9sRN1Ehl06Gc/giphy.gif)

___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2021-08-12 17:27 UTC, ahmetbozaci commented on index.html
> +      </a>
- [ ] For this link please follow the button styling: Active, Hover and Pressed (see design)

- [ ] Also align button like in desing.

![image](https://user-images.githubusercontent.com/38635158/129240688-a3e4039a-84c0-480d-9f46-18adf39cdc24.png)
___
**ORİGİNAL:**
![image](https://user-images.githubusercontent.com/38635158/129240758-d07a9d5e-e9ff-430e-a8c4-b71fd543c14a.png)

2021-08-12 17:27 UTC, ahmetbozaci commented on style.css
> +  font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
- [ ] You should stick design. Original design for is different. Please change it. Check other font family in your page.
- [ ] Also you can combine these style and use in HTML.` .font{font-family: ''}`  and you can use font class in HTML. (OPTIONAL)

2021-08-12 17:27 UTC, ahmetbozaci commented on style.css
> +}
- [ ] You should use `flexbox` for align  **all projects.**

2021-08-12 17:27 UTC, ahmetbozaci commented on style.css
> +}
- [ ] You should use `flexbox` for align  **all projects.**

2021-08-12 17:27 UTC, ahmetbozaci commented on index.html
> +          See Project
- [ ] You should follow the button styling: Active, Hover and Pressed 
Check the other buttons in your page and please do for all of them. It is just one example

2021-08-12 17:27 UTC, ahmetbozaci commented on style.css
> +  position: relative;
- [ ] You should use `flexbox` for align skills section. Check other in page and use `flexbox` for all of them.

2021-08-12 17:44 UTC, Ahmed-Alfaouq commented on style.css
> +}
@ahmetbozaci
I'm sorry, but I didn't understand this one. can you tell me more, please?

2021-08-12 18:14 UTC, Ahmed-Alfaouq commented on style.css
> +  font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
@ahmetbozaci
I can not find the font on my device so it shows errors when I use stylelint. Because I do not have that font. 
can u tell me what should I do, please?

2021-08-12 18:20 UTC, ahmetbozaci commented on style.css
> +  font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
@Ahmed-Alfaouq Example for my recent works text font family is [Crete Round] (https://fonts.google.com/specimen/Crete+Round). You can see in right section in figma website.
![image](https://user-images.githubusercontent.com/38635158/129248238-50c7665a-1fdf-4f9c-b460-92a39cbf98ab.png)

2021-08-12 18:21 UTC, ahmetbozaci commented on style.css
> +}
@Ahmed-Alfaouq For about section you should align items with flexbox. I cant see any flexbox in about section.

2021-08-12 19:04 UTC, Ahmed-Alfaouq commented on style.css
> +  position: relative;
@ahmetbozaci
Hi sir,
I made all the changes. Can you please take a look and tell me if I have to change anything else?
Thanks.

2021-08-12 19:46 UTC, ahmetbozaci commented on style.css
> +  position: relative;
Hello @Ahmed-Alfaouq  please send code request from your dashboard. Next TSE will check.

2021-08-13 04:11 UTC, AshakaE approved these changes
### Hi @Ahmed-Alfaouq  🙋‍♀️, 

# STATUS APPROVED ✔
Thanks for making the required changes
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 06:42 UTC, merged